export interface Word {
  id: string
  en: string
  he: string
  he_find: string
  category: string
  image: string
  source: string
  color?: string
}
export interface Pack {
  id: string
  name: string
  name_he: string
  known: boolean
  order: number
  words: Word[]
}

const modules = import.meta.glob<{ default: Pack }>('./packs/*.json', { eager: true })
export const PACKS: Pack[] = Object.values(modules)
  .map((m) => m.default)
  .sort((a, b) => a.order - b.order)
export const WORDS: Word[] = PACKS.flatMap((p) => p.words)
export const WORD_BY_ID: Record<string, Word> = Object.fromEntries(WORDS.map((w) => [w.id, w]))
export const PACK_BY_ID: Record<string, Pack> = Object.fromEntries(PACKS.map((p) => [p.id, p]))

export const BASE = import.meta.env.BASE_URL
export const img = (path: string) => BASE + path
export const wordImg = (w: Word) => BASE + w.image
export const isPhoto = (w: Word) => w.source === 'photo'

/** audio path helpers – all files are pre-generated by scripts/gen_audio.py */
export const A = {
  word: (id: string) => `audio/words/${id}.mp3`,
  slow: (id: string) => `audio/words/${id}_slow.mp3`,
  he: (id: string) => `audio/words/${id}_he.mp3`,
  find: (id: string) => `audio/words/${id}_find.mp3`,
  findHe: (id: string) => `audio/words/${id}_find_he.mp3`,
  pop: (id: string) => `audio/words/${id}_pop.mp3`,
  where: (id: string) => `audio/words/${id}_where.mp3`,
  color: (id: string) => `audio/words/${id}_color.mp3`,
  colorHe: (id: string) => `audio/words/${id}_color_he.mp3`,
  ui: (key: string) => `audio/ui/${key}.mp3`,
  uiHe: (key: string) => `audio/ui/${key}_he.mp3`,
  sticker: (id: string) => `audio/stickers/${id}.mp3`,
  stickerHe: (id: string) => `audio/stickers/${id}_he.mp3`,
}
export const PRAISES = ['praise_1', 'praise_2', 'praise_3', 'praise_4', 'praise_5', 'praise_6', 'praise_7']

export const STICKER_INFO: Record<string, { en: string; he: string }> = {
  trex: { en: 'T-rex', he: 'טי-רקס' },
  sauropod: { en: 'long-neck dinosaur', he: 'דינוזאור ארוך צוואר' },
  car: { en: 'car', he: 'מכונית' },
  racecar: { en: 'race car', he: 'מכונית מרוץ' },
  lion: { en: 'lion', he: 'אריה' },
  tiger: { en: 'tiger', he: 'נמר' },
  dog: { en: 'dog', he: 'כלב' },
  cat: { en: 'cat', he: 'חתול' },
  unicorn: { en: 'unicorn', he: 'חד-קרן' },
  dragon: { en: 'dragon', he: 'דרקון' },
  rocket: { en: 'rocket', he: 'רקטה' },
  firetruck: { en: 'fire truck', he: 'כבאית' },
  police: { en: 'police car', he: 'ניידת משטרה' },
  tractor: { en: 'tractor', he: 'טרקטור' },
  panda: { en: 'panda', he: 'פנדה' },
  koala: { en: 'koala', he: 'קואלה' },
  frog: { en: 'frog', he: 'צפרדע' },
  whale: { en: 'whale', he: 'לווייתן' },
  turtle: { en: 'turtle', he: 'צב' },
  octopus: { en: 'octopus', he: 'תמנון' },
  bus: { en: 'bus', he: 'אוטובוס' },
  train: { en: 'train', he: 'רכבת' },
  plane: { en: 'airplane', he: 'מטוס' },
  helicopter: { en: 'helicopter', he: 'מסוק' },
  monkey: { en: 'monkey', he: 'קוף' },
  penguin: { en: 'penguin', he: 'פינגווין' },
  bear: { en: 'bear', he: 'דוב' },
  fox: { en: 'fox', he: 'שועל' },
  giraffe: { en: 'giraffe', he: 'ג׳ירפה' },
  zebra: { en: 'zebra', he: 'זברה' },
  star: { en: 'star', he: 'כוכב' },
  trophy: { en: 'trophy', he: 'גביע' },
  rainbow: { en: 'rainbow', he: 'קשת' },
  crown: { en: 'crown', he: 'כתר' },
  robot: { en: 'robot', he: 'רובוט' },
  crocodile: { en: 'crocodile', he: 'תנין' },
  shark: { en: 'shark', he: 'כריש' },
  owl: { en: 'owl', he: 'ינשוף' },
  butterfly: { en: 'butterfly', he: 'פרפר' },
  sailboat: { en: 'sailboat', he: 'סירת מפרש' },
}
export const STICKERS = Object.keys(STICKER_INFO)
export const AVATARS = ['a1', 'a2', 'a3', 'a4', 'a5', 'a6', 'a7', 'a8']
